### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Yannic** [cgrushko/proto_library#16]
It would be great if this repo had a license.

@cgrushko @ejona86 @ittaiz @erickj Would you be okay with adding a `Apache 2` license?

**Comment by cgrushko** [comment]
I'm fine with Apache 2

**Comment by ejona86** [comment]
Apache 2 is good with me.

**Comment by ittaiz** [comment]
sure thing. I'm fine with Apache 2

**Comment by Yannic** [comment]
@erickj Would you be okay with adding a `Apache 2` license?

**Comment by erickj** [comment]
Yes Apache 2 license is fine with me
