### ISSUE TITLE
Reference to "google/api/annotations.proto"

### ISSUE THREAD

**Issue by ghost** [cgrushko/proto_library#8]
Hi, 

is there a sample/advice how to add a reference to 

import "google/api/annotations.proto";

It seems to be a trivial case, but I'm not able to find a way how to add the above reference to my project. 

Thank you. 

Best Regards, 
Jiri

**Comment by cgrushko** [comment]
Can you re-ask the question on StackOverflow and post the link here? it'll make it more discoverable and allow others to chime in. 
Also, some details are missing - are you using googleapi as an external repository? do you vendor it?

**Comment by ghost** [comment]
Thank you for your Feedback. I posted the question on StackOverflow - https://stackoverflow.com/questions/47930973/grpc-bazel-envoy-json-proxy-how-to-import-google-api-annotations-proto

Regards, 
jj

**Comment by cgrushko** [comment]
Answered there; it's a sad state we have, hopefully the answer is better than nothing...
